name: "Apk size tracker"
description: "Track the size of apk"
inputs:
  flavor: # id of input
    description: "flavor of the apk to build"
    required: true
    default: "staging"
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  threshold:
    description: "Permissible size threshold above which merging will be blocked"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
